package com.jpr.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jpr.greendaodemo.bean.User;
import com.jpr.greendaodemo.bean.Student;
import com.jpr.greendaodemo.bean.IdCard;
import com.jpr.greendaodemo.bean.CreditCard;

import com.jpr.greendaodemo.db.UserDao;
import com.jpr.greendaodemo.db.StudentDao;
import com.jpr.greendaodemo.db.IdCardDao;
import com.jpr.greendaodemo.db.CreditCardDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig idCardDaoConfig;
    private final DaoConfig creditCardDaoConfig;

    private final UserDao userDao;
    private final StudentDao studentDao;
    private final IdCardDao idCardDao;
    private final CreditCardDao creditCardDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        idCardDaoConfig = daoConfigMap.get(IdCardDao.class).clone();
        idCardDaoConfig.initIdentityScope(type);

        creditCardDaoConfig = daoConfigMap.get(CreditCardDao.class).clone();
        creditCardDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        idCardDao = new IdCardDao(idCardDaoConfig, this);
        creditCardDao = new CreditCardDao(creditCardDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Student.class, studentDao);
        registerDao(IdCard.class, idCardDao);
        registerDao(CreditCard.class, creditCardDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        idCardDaoConfig.clearIdentityScope();
        creditCardDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public IdCardDao getIdCardDao() {
        return idCardDao;
    }

    public CreditCardDao getCreditCardDao() {
        return creditCardDao;
    }

}
